#!/usr/bin/env python3
"""Generate repository file inventory, Markdown index, and SHA-256 checksums.

Run from the repository root. Generated outputs intentionally exclude themselves and
Git metadata so repeated runs are deterministic.
"""

from __future__ import annotations

import hashlib
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUTS = {"MANIFEST_FILES.txt", "FILE_INDEX.md", "SHA256SUMS"}
EXCLUDED_PARTS = {".git", ".next", "node_modules", "target", "dist", "build", ".venv"}


def included(path: Path) -> bool:
    relative = path.relative_to(ROOT)
    if relative.as_posix() in OUTPUTS:
        return False
    return not any(part in EXCLUDED_PARTS for part in relative.parts)


def files() -> list[Path]:
    return sorted(
        (path for path in ROOT.rglob("*") if path.is_file() and included(path)),
        key=lambda path: path.relative_to(ROOT).as_posix(),
    )


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_manifest(paths: list[Path]) -> None:
    text = "\n".join(path.relative_to(ROOT).as_posix() for path in paths) + "\n"
    (ROOT / "MANIFEST_FILES.txt").write_text(text, encoding="utf-8")


def write_checksums(paths: list[Path]) -> None:
    lines = [f"{sha256(path)}  {path.relative_to(ROOT).as_posix()}" for path in paths]
    (ROOT / "SHA256SUMS").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_index(paths: list[Path]) -> None:
    groups: dict[str, list[str]] = defaultdict(list)
    for path in paths:
        relative = path.relative_to(ROOT).as_posix()
        group = relative.split("/", 1)[0] if "/" in relative else "(root)"
        groups[group].append(relative)

    lines = [
        "# Repository File Index",
        "",
        "> Generated by `scripts/repository/generate_repository_metadata.py`. Do not edit manually.",
        "",
        f"Total files: **{len(paths)}**",
        "",
    ]
    for group in sorted(groups):
        lines.extend([f"## {group}", ""])
        lines.extend(f"- `{item}`" for item in groups[group])
        lines.append("")
    (ROOT / "FILE_INDEX.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    paths = files()
    write_manifest(paths)
    write_checksums(paths)
    write_index(paths)
    print(f"Generated metadata for {len(paths)} files.")


if __name__ == "__main__":
    main()
