#!/usr/bin/env python3
"""Regenerate conformance/vibeproof/v1/ed25519-divergence-corpus.json.

Why this corpus exists
----------------------
Citing RFC 8032 does not pin Ed25519 verification. Section 5.1.7 says that
checking the cofactored group equation `[8][S]B = [8]R + [8][k]A` is
"sufficient, but not required", which permits the cofactorless
`[S]B = R + [k]A` instead, and Section 8.8 concedes that implementations then
"disagree about the exact set of valid signatures". FIPS 186-5 Section 7.7
reproduces the same permission verbatim, so citing FIPS resolves nothing
either. A cofactored verifier accepts a strictly larger set than a cofactorless
one and the implication runs one way only, so a Rust signer and a Go verifier
that both conform to RFC 8032 can disagree.

RFC 8032's own test vectors cannot detect any of that. They are well-formed
signatures that pass under every implementation, which is exactly why they
prove nothing about the axes that diverge. Only adversarial inputs separate the
criteria sets, and D-192 pins VibeProof v1 to ZIP-215:

* `A` and `R` are points on Ed25519; non-canonical `y` encodings are accepted;
* `S` MUST be an integer strictly less than the group order `l`;
* the cofactored equation `[8][S]B = [8]R + [8][k]A` MUST hold.

What this generator does and does not establish
-----------------------------------------------
It builds each case deterministically from a recorded seed, so the corpus is
byte-reproducible and no verdict is hand-typed. It computes two verdicts per
case from its own curve arithmetic: the ZIP-215 verdict and the verdict of a
strict RFC 8032 cofactorless verifier.

A self-written reference is the weakest kind of evidence a corpus can carry:
if the same misreading is in the generator and in the specification comment
beside it, both agree and neither is right. So the ZIP-215 verdicts are
confirmed against an independent implementation and the confirmation is
recorded per case in `conformance/vibeproof/v1/zip215-oracle-run.json`, keyed
by a digest of the exact case bytes. A case whose digest is not covered by that
run is emitted as `unconfirmed` and carries the command that would confirm it.
Where the oracle contradicts the computed verdict this generator refuses to
write the corpus at all, because a corpus that records a verdict its own oracle
disputes is worse than no corpus.

Usage:
    generate_ed25519_divergence_corpus.py            # rewrite the corpus
    generate_ed25519_divergence_corpus.py --check    # exit 1 if it differs
"""

from __future__ import annotations

import argparse
import functools
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CORPUS = ROOT / "conformance" / "vibeproof" / "v1" / "ed25519-divergence-corpus.json"
ORACLE_RUN = ROOT / "conformance" / "vibeproof" / "v1" / "zip215-oracle-run.json"
ORACLE_RUN_RELATIVE = "conformance/vibeproof/v1/zip215-oracle-run.json"
ORACLE_COMMAND = "go run ./conformance/vibeproof/v1/zip215-oracle"

# --- Ed25519 domain parameters -------------------------------------------------
#
# RFC 8032 Section 5.1. Every constant below is either written out by that
# section or derived here from one that is; nothing is pasted from a corpus
# whose derivation this file cannot show.

P = 2**255 - 19
D = (-121665 * pow(121666, P - 2, P)) % P
# l = 2^252 + 27742317777372353535851937790883648493, the prime order of the
# subgroup generated by B. The full curve group has order 8*l; that factor of 8
# is the cofactor the two verification equations disagree about.
L = 2**252 + 27742317777372353535851937790883648493
COFACTOR = 8
SQRT_MINUS_ONE = pow(2, (P - 1) // 4, P)

# The recorded inputs. Changing any of them changes the corpus, which is the
# point: the corpus is a function of these and of the code below, and of nothing
# else. The seed is test-only and matches `exact-byte-vectors.json` so both
# corpora describe the same signer.
SIGNER_SEED = bytes.fromhex(
    "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
)
MESSAGE = b"VIBEPROOF/V1 ED25519 DIVERGENCE CORPUS"

# Two throwaway scalars used where a case needs some point of known discrete
# log and the specific value carries no meaning. Recorded rather than drawn, so
# the corpus does not move when a random source does.
NONCE_A = 12345
NONCE_B = 777


# --- curve arithmetic ----------------------------------------------------------


def recover_x(y: int, sign: int) -> int | None:
    """Solve the curve equation for x, or return None when y is not on it.

    Ed25519 is -x^2 + y^2 = 1 + d x^2 y^2, so x^2 = (y^2 - 1)/(d y^2 + 1).
    RFC 8032 Section 5.1.3 takes the candidate root as (u/v)^((p+3)/8) and
    multiplies by sqrt(-1) when that misses, because p = 5 (mod 8) leaves no
    single exponent that always lands.
    """
    yy = (y * y) % P
    u = (yy - 1) % P
    v = (D * yy + 1) % P
    if v == 0:
        return None
    xx = (u * pow(v, P - 2, P)) % P
    x = pow(xx, (P + 3) // 8, P)
    if (x * x - xx) % P != 0:
        x = (x * SQRT_MINUS_ONE) % P
    if (x * x - xx) % P != 0:
        return None
    if x % 2 != sign:
        x = (-x) % P
    return x


Point = tuple[int, int]
IDENTITY: Point = (0, 1)


def point_add(first: Point, second: Point) -> Point:
    x1, y1 = first
    x2, y2 = second
    k = (D * x1 * x2 * y1 * y2) % P
    x3 = ((x1 * y2 + x2 * y1) * pow(1 + k, P - 2, P)) % P
    y3 = ((y1 * y2 + x1 * x2) * pow(1 - k, P - 2, P)) % P
    return x3, y3


def point_mul(point: Point, scalar: int) -> Point:
    result = IDENTITY
    addend = point
    while scalar:
        if scalar & 1:
            result = point_add(result, addend)
        addend = point_add(addend, addend)
        scalar >>= 1
    return result


def encode_point(point: Point) -> bytes:
    """RFC 8032 Section 5.1.2: little-endian y with the low bit of x on top."""
    x, y = point
    encoded = bytearray(y.to_bytes(32, "little"))
    encoded[31] |= (x & 1) << 7
    return bytes(encoded)


def decode_point(encoded: bytes) -> Point | None:
    """Decode under the ZIP-215 rule: the 255-bit y is taken modulo p.

    This is the whole non-canonical question in one line. RFC 8032 Section
    5.1.3 says decoding fails when the recovered y is at least p; ZIP-215 says
    reduce it and carry on, which admits the 19 residues 0..18 under a second
    encoding each. `decode_point_canonical` below is the other rule, so the
    two are stated separately rather than being one function with a flag whose
    default a reader has to go and find.
    """
    raw = int.from_bytes(encoded, "little")
    sign = raw >> 255
    y = (raw & (2**255 - 1)) % P
    x = recover_x(y, sign)
    if x is None:
        return None
    return x, y


def is_canonical_encoding(encoded: bytes) -> bool:
    return (int.from_bytes(encoded, "little") & (2**255 - 1)) < P


def decode_point_canonical(encoded: bytes) -> Point | None:
    if not is_canonical_encoding(encoded):
        return None
    return decode_point(encoded)


BASE_Y = (4 * pow(5, P - 2, P)) % P
BASE: Point = (recover_x(BASE_Y, 0) or 0, BASE_Y)


def torsion_order(point: Point) -> int | None:
    """The order of a point when it divides 8, else None."""
    for candidate in (1, 2, 4, 8):
        if point_mul(point, candidate) == IDENTITY:
            return candidate
    return None


def classify_point(point: Point) -> str:
    """Name the subgroup a point sits in, in the vocabulary the cases use."""
    small = torsion_order(point)
    if small == 1:
        return "identity"
    if small is not None:
        return f"small-order-{small}"
    if point_mul(point, L) == IDENTITY:
        return "prime-order"
    return "mixed-order"


# Both derivations below are pure and cost a few hundred scalar multiplications
# in Python, so they are memoised. The cache is an optimisation only: every call
# recomputes the same set from the same constants.
@functools.cache
def eight_torsion() -> tuple[Point, ...]:
    """Derive the eight points of order dividing 8 instead of pasting them.

    The curve group has order 8*l with l prime, so for any point P the point
    [l]P lies in the 8-torsion, and [l]P has order 8 for any P outside the
    subgroups of index 2 and 4. Searching the smallest y values for a curve
    point and multiplying by l therefore lands on a generator of the torsion in
    a couple of tries; its multiples are the whole set. y = 3 is the first y
    that works, which is a fact about this curve and not an input.
    """
    for y in range(2, 1000):
        x = recover_x(y, 0)
        if x is None:
            continue
        candidate = point_mul((x, y), L)
        if torsion_order(candidate) == 8:
            points = []
            current = IDENTITY
            for _ in range(8):
                points.append(current)
                current = point_add(current, candidate)
            return tuple(points)
    raise RuntimeError("no generator of the 8-torsion found")


@functools.cache
def non_canonical_curve_points() -> tuple[dict, ...]:
    """Enumerate every non-canonical y encoding that decodes to a curve point.

    A non-canonical encoding is one whose 255-bit y field holds p..2^255-1, so
    exactly the 19 residues 0..18 have one. Only some of those are on the
    curve, and the set is small enough to enumerate exhaustively rather than
    assert. Two of them are in the 8-torsion and the rest are not, which is why
    a non-canonical `A` case and a small-order `A` case are different cases
    even though the cheapest example of each is the same point.
    """
    found = []
    for raw in range(P, 2**255):
        for sign in (0, 1):
            point = decode_point(
                raw.to_bytes(32, "little")
                if sign == 0
                else (raw | (1 << 255)).to_bytes(32, "little")
            )
            if point is None:
                continue
            found.append(
                {
                    "encoding_hex": (raw if sign == 0 else raw | (1 << 255))
                    .to_bytes(32, "little")
                    .hex(),
                    "reduced_y": raw - P,
                    "point_class": classify_point(point),
                }
            )
    return tuple(found)


# --- signing -------------------------------------------------------------------


def clamp(scalar_bytes: bytes) -> int:
    """RFC 8032 Section 5.1.5 pruning: clear the low 3 bits, set bit 254."""
    scalar = int.from_bytes(scalar_bytes, "little")
    scalar &= (1 << 254) - 8
    scalar |= 1 << 254
    return scalar


def expand_seed(seed: bytes) -> tuple[int, bytes]:
    digest = hashlib.sha512(seed).digest()
    return clamp(digest[:32]), digest[32:]


def challenge(r_bytes: bytes, a_bytes: bytes, message: bytes) -> int:
    """k = SHA-512(R || A || M) mod l, over the encodings as transmitted.

    "As transmitted" is load-bearing: a non-canonical R or A is hashed in the
    form it arrived in, so re-encoding a decoded point before hashing produces
    a different k and silently fails every non-canonical case.
    """
    return (
        int.from_bytes(hashlib.sha512(r_bytes + a_bytes + message).digest(), "little")
        % L
    )


# --- the two verification rules ------------------------------------------------


def verify_zip215(
    a_bytes: bytes, r_bytes: bytes, s_bytes: bytes, message: bytes
) -> tuple[bool, str]:
    """ZIP-215, as D-192 pins it. Returns (verdict, the rule that decided it)."""
    point_a = decode_point(a_bytes)
    if point_a is None:
        return False, "A does not decode to a curve point"
    point_r = decode_point(r_bytes)
    if point_r is None:
        return False, "R does not decode to a curve point"
    s = int.from_bytes(s_bytes, "little")
    if s >= L:
        return False, "S is not less than l"
    k = challenge(r_bytes, a_bytes, message)
    left = point_mul(point_mul(BASE, s), COFACTOR)
    right = point_add(
        point_mul(point_r, COFACTOR), point_mul(point_mul(point_a, k), COFACTOR)
    )
    if left != right:
        return False, "cofactored equation does not hold"
    return True, "cofactored equation holds"


def verify_cofactorless(
    a_bytes: bytes, r_bytes: bytes, s_bytes: bytes, message: bytes
) -> tuple[bool, str]:
    """Strict RFC 8032: canonical decoding, S < l, and `[S]B = R + [k]A`.

    This is the *strict* reading of Sections 5.1.3 and 5.1.7 and not a model of
    any particular library. Deployed cofactorless verifiers vary underneath it -
    OpenSSL accepts some non-canonical encodings this rejects, and libsodium
    rejects small-order keys this would accept - which is the disagreement the
    corpus exists to make visible. The oracle run records what two real
    cofactorless implementations actually answered.
    """
    point_a = decode_point_canonical(a_bytes)
    if point_a is None:
        return False, "A is non-canonical or not a curve point"
    point_r = decode_point_canonical(r_bytes)
    if point_r is None:
        return False, "R is non-canonical or not a curve point"
    s = int.from_bytes(s_bytes, "little")
    if s >= L:
        return False, "S is not less than l"
    k = challenge(r_bytes, a_bytes, message)
    if point_mul(BASE, s) != point_add(point_r, point_mul(point_a, k)):
        return False, "cofactorless equation does not hold"
    return True, "cofactorless equation holds"


# --- case construction ---------------------------------------------------------


def build_cases() -> list[dict]:
    """Construct every case from the recorded inputs.

    Each case names the axis it isolates. The constructions are not arbitrary:
    where a case has to produce a signature that a cofactored verifier accepts,
    it exploits the fact that [8]T is the identity for any T in the 8-torsion,
    so the torsion component of R or A vanishes from the cofactored equation
    and survives in the cofactorless one. That is the divergence, written down.
    """
    secret, prefix = expand_seed(SIGNER_SEED)
    public = point_mul(BASE, secret)
    public_bytes = encode_point(public)

    torsion = eight_torsion()
    order_eight = next(point for point in torsion if torsion_order(point) == 8)

    # A genuine RFC 8032 signature over MESSAGE, used as the control and as the
    # base of the two S >= l cases.
    nonce = int.from_bytes(hashlib.sha512(prefix + MESSAGE).digest(), "little") % L
    r_valid = encode_point(point_mul(BASE, nonce))
    s_valid = (nonce + challenge(r_valid, public_bytes, MESSAGE) * secret) % L

    # Non-canonical encodings, derived rather than pasted: the identity has the
    # second encoding y = p + 1, and the order-4 point (x, 0) has y = p.
    non_canonical_identity = (P + 1).to_bytes(32, "little")
    non_canonical_order_four = P.to_bytes(32, "little")
    # y = p + 3 reduces to y = 3, which is on the curve and is *not* in the
    # 8-torsion. It is here to stop "non-canonical encodings are accepted"
    # being read as "non-canonical encodings verify".
    non_canonical_mixed = (P + 3).to_bytes(32, "little")

    def with_torsion_r(r_bytes: bytes) -> bytes:
        """S that satisfies the cofactored equation for a torsion R.

        [8][S]B = [8]R + [8][k]A collapses to [8][S]B = [8][k]A when R is in
        the 8-torsion, so S = k*a mod l works and the cofactorless equation,
        which still carries R, cannot hold unless R is the identity.
        """
        k = challenge(r_bytes, public_bytes, MESSAGE)
        return ((k * secret) % L).to_bytes(32, "little")

    nonce_a_r = encode_point(point_mul(BASE, NONCE_A))
    nonce_b_r = encode_point(point_mul(BASE, NONCE_B))

    return [
        {
            "id": "control-canonical-valid",
            "axis": "control",
            "a": public_bytes,
            "r": r_valid,
            "s": s_valid.to_bytes(32, "little"),
            "intent": (
                "A well-formed RFC 8032 signature. It is in the corpus to be the "
                "thing every other case is measured against: it passes under both "
                "criteria, which is exactly why RFC 8032's own vectors prove nothing."
            ),
        },
        {
            "id": "non-canonical-a-identity",
            "axis": "non-canonical-A",
            "a": non_canonical_identity,
            "r": nonce_a_r,
            "s": (NONCE_A % L).to_bytes(32, "little"),
            "intent": (
                "A is the identity written as y = p + 1, an unreduced encoding. "
                "[k]A is the identity either way, so both group equations hold and "
                "the only thing that can separate the two verifiers is whether they "
                "accept the encoding. This isolates the non-canonical-A axis with "
                "the cofactor held out of it."
            ),
        },
        {
            "id": "non-canonical-a-mixed-order",
            "axis": "non-canonical-A",
            "a": non_canonical_mixed,
            "r": nonce_a_r,
            "s": (NONCE_A % L).to_bytes(32, "little"),
            "intent": (
                "A is y = p + 3, an unreduced encoding of a point that is on the "
                "curve and outside the 8-torsion. ZIP-215 accepts the encoding and "
                "then rejects the signature, because accepting a non-canonical point "
                "is not accepting a signature over it. A verifier that skips the "
                "check rather than performing it passes the case above and fails here."
            ),
        },
        {
            "id": "non-canonical-r-identity",
            "axis": "non-canonical-R",
            "a": public_bytes,
            "r": non_canonical_identity,
            "s": with_torsion_r(non_canonical_identity),
            "intent": (
                "R is the identity written as y = p + 1: a y-coordinate unreduced "
                "modulo 2^255 - 19. Both group equations hold, so as with the A case "
                "the encoding rule alone decides. It also separates the two shapes of "
                "cofactorless verifier, because one that recomputes R' and compares "
                "encodings can never match a non-canonical R even when the equation holds."
            ),
        },
        {
            "id": "non-canonical-r-order4",
            "axis": "non-canonical-R",
            "a": public_bytes,
            "r": non_canonical_order_four,
            "s": with_torsion_r(non_canonical_order_four),
            "intent": (
                "R is y = p, the unreduced encoding of an order-4 point. The cofactor "
                "annihilates R and the cofactored equation holds; the cofactorless one "
                "carries the order-4 component and fails. Non-canonical encoding and "
                "cofactor are both in play here, which is why the identity case above "
                "exists to separate them."
            ),
        },
        {
            "id": "small-order-a-order8",
            "axis": "small-order-A",
            "a": encode_point(order_eight),
            "r": nonce_b_r,
            "s": (NONCE_B % L).to_bytes(32, "little"),
            "intent": (
                "A is a canonically encoded point of order 8. [8]A is the identity so "
                "A drops out of the cofactored equation entirely and the signature "
                "verifies; the cofactorless equation keeps [k]A and fails. ZIP-215 "
                "carries no excluded-point list, so this is accepted by rule and not "
                "by oversight."
            ),
        },
        {
            "id": "cofactored-only-order8-r",
            "axis": "cofactor",
            "a": public_bytes,
            "r": encode_point(order_eight),
            "s": with_torsion_r(encode_point(order_eight)),
            "intent": (
                "Every byte is canonical, A is an ordinary public key, and the two "
                "criteria still disagree. R is an order-8 point that the cofactor "
                "annihilates. This is the case that shows the divergence is not a "
                "story about malformed encodings: it is the group equation itself."
            ),
        },
        {
            "id": "s-equals-l",
            "axis": "S-not-less-than-l",
            "a": public_bytes,
            "r": r_valid,
            "s": L.to_bytes(32, "little"),
            "intent": (
                "S = l exactly, the first excluded value. ZIP-215 requires S < l and "
                "so does RFC 8032 Section 5.1.7, so the two agree here - which is the "
                "point worth recording, because ZIP-215 is not uniformly more "
                "permissive and an implementer who reads it that way drops the one "
                "range check that stops malleability."
            ),
        },
        {
            "id": "s-plus-l",
            "axis": "S-not-less-than-l",
            "a": public_bytes,
            "r": r_valid,
            "s": (s_valid + L).to_bytes(32, "little"),
            "intent": (
                "The control signature with l added to S. S mod l is the valid scalar, "
                "so the group equation would hold if the range check were skipped or "
                "the scalar reduced first, and the case therefore fails for the range "
                "rule and for nothing else. Historic ref10-derived verifiers accept it."
            ),
        },
    ]


# --- corpus assembly -----------------------------------------------------------


def case_digest(case: dict) -> str:
    """Bind a confirmation to the exact bytes it was made against.

    The oracle records this digest per case. A confirmation that does not name
    the digest of the case it is attached to is a confirmation of whatever the
    corpus happened to say when it was pasted in.
    """
    material = b"|".join(
        (
            case["id"].encode("ascii"),
            case["a"],
            case["r"],
            case["s"],
            MESSAGE,
        )
    )
    return hashlib.sha256(material).hexdigest()


def load_oracle_run() -> tuple[dict, dict[str, dict]]:
    if not ORACLE_RUN.is_file():
        return {}, {}
    document = json.loads(ORACLE_RUN.read_text(encoding="utf-8"))
    provenance = {key: value for key, value in document.items() if key != "results"}
    results = {entry["case_id"]: entry for entry in document.get("results", [])}
    return provenance, results


def render_case(case: dict, oracle: dict[str, dict]) -> dict:
    a_bytes, r_bytes, s_bytes = case["a"], case["r"], case["s"]
    zip215_verdict, zip215_rule = verify_zip215(a_bytes, r_bytes, s_bytes, MESSAGE)
    classic_verdict, classic_rule = verify_cofactorless(
        a_bytes, r_bytes, s_bytes, MESSAGE
    )

    digest = case_digest(case)
    entry = oracle.get(case["id"])
    confirmed = bool(entry) and entry.get("case_digest") == digest

    if confirmed:
        oracle_verdict = entry["zip215_verdict"]
        computed = "accept" if zip215_verdict else "reject"
        if oracle_verdict != computed:
            raise SystemExit(
                f"{case['id']}: the ZIP-215 oracle answered {oracle_verdict} and this "
                f"generator computed {computed}. One of them is wrong and the corpus "
                f"is not written until that is resolved."
            )
        confirmation = {
            "status": "confirmed",
            "confirmed_by": entry["oracle_id"],
            "oracle_verdict": oracle_verdict,
        }
    else:
        confirmation = {
            "status": "unconfirmed",
            "reason": (
                "no ZIP-215 oracle result is recorded against this case's digest"
                if entry is None
                else "the recorded oracle result was made against different case bytes"
            ),
            "confirmation_path": (
                f"run `{ORACLE_COMMAND}` and commit the refreshed "
                f"{ORACLE_RUN_RELATIVE}, which verifies this case under "
                f"github.com/hdevalence/ed25519consensus and records the verdict "
                f"against its case_digest"
            ),
        }

    point_a = decode_point(a_bytes)
    point_r = decode_point(r_bytes)

    zip215_word = "accept" if zip215_verdict else "reject"
    observed = (
        oracle[case["id"]]["cofactorless_observations"]
        if case["id"] in oracle and oracle[case["id"]].get("case_digest") == digest
        else []
    )
    # Two different divergences, kept apart because collapsing them into one
    # boolean would state a falsehood. `non-canonical-a-identity` diverges from
    # the strict text of RFC 8032 s5.1.3 and from no deployed verifier measured
    # here, because both of them accept an encoding the text says must fail to
    # decode. A corpus that called that "cofactorless rejects it" would be
    # asserting a verdict from prose, which is the defect it exists to avoid.
    divergence = {
        "against_strict_rfc8032": zip215_verdict != classic_verdict,
        "against_observed_cofactorless": sorted(
            observation["implementation"]
            for observation in observed
            if observation["verdict"] != zip215_word
        ),
    }

    return {
        "id": case["id"],
        "axis": case["axis"],
        "intent": case["intent"],
        "public_key_hex": a_bytes.hex(),
        "signature_hex": (r_bytes + s_bytes).hex(),
        "message_hex": MESSAGE.hex(),
        "case_digest": digest,
        "decoded": {
            "a_encoding": "canonical"
            if is_canonical_encoding(a_bytes)
            else "non-canonical",
            "a_point": classify_point(point_a) if point_a else "not-on-curve",
            "r_encoding": "canonical"
            if is_canonical_encoding(r_bytes)
            else "non-canonical",
            "r_point": classify_point(point_r) if point_r else "not-on-curve",
            "s_less_than_l": int.from_bytes(s_bytes, "little") < L,
        },
        "zip215": {
            "verdict": zip215_word,
            "deciding_rule": zip215_rule,
            "confirmation": confirmation,
        },
        "cofactorless": {
            "verdict": "accept" if classic_verdict else "reject",
            "deciding_rule": classic_rule,
            "source": "computed by this generator from strict RFC 8032 s5.1.3 and s5.1.7",
            "observed": observed,
        },
        "divergence": divergence,
    }


def regenerate() -> str:
    provenance, oracle = load_oracle_run()
    cases = build_cases()
    rendered = [render_case(case, oracle) for case in cases]

    axes = sorted({case["axis"] for case in cases})
    required = {
        "non-canonical-A",
        "non-canonical-R",
        "small-order-A",
        "S-not-less-than-l",
    }
    missing = required - set(axes)
    if missing:
        raise SystemExit(f"corpus does not cover required axes: {sorted(missing)}")

    document = {
        "schema_version": 1,
        "corpus_id": "vibeproof-v1-ed25519-divergence-001",
        "generator": "scripts/repository/generate_ed25519_divergence_corpus.py",
        "normative_rule": "ZIP-215",
        "normative_owner": "docs/architecture/VIBEPROOF_V1_PROTOCOL.md",
        "decision": "D-192",
        "authority_class": "normative-planning",
        "evidence_ceiling": "fixture-consistent",
        "scope": (
            "raw Ed25519 signature verification only. The COSE_Sign1 and canonical "
            "CBOR bindings are owned by exact-byte-vectors.json; a message here is "
            "fixed ASCII so a failure localises to the verification rule and not to "
            "an encoder."
        ),
        "not_evidence_of": [
            "any implementation being conformant, because no implementation consumes this corpus yet",
            "cross-language parity, which requires two implementations to run it",
            "security or launch readiness of any kind",
        ],
        "inputs": {
            "signer_seed_hex": SIGNER_SEED.hex(),
            "message_ascii": MESSAGE.decode("ascii"),
            "message_hex": MESSAGE.hex(),
            "nonce_a": NONCE_A,
            "nonce_b": NONCE_B,
        },
        "derived_facts": {
            "l": str(L),
            "cofactor": COFACTOR,
            "eight_torsion": [
                {
                    "encoding_hex": encode_point(point).hex(),
                    "order": torsion_order(point),
                }
                for point in eight_torsion()
            ],
            "non_canonical_curve_points": list(non_canonical_curve_points()),
        },
        "zip215_confirmation": provenance
        or {
            "status": "absent",
            "detail": (
                f"{ORACLE_RUN_RELATIVE} is not present, so every ZIP-215 verdict in "
                f"this corpus is unconfirmed"
            ),
        },
        "case_count": len(rendered),
        "confirmed_case_count": sum(
            1
            for case in rendered
            if case["zip215"]["confirmation"]["status"] == "confirmed"
        ),
        "diverging_case_count": sum(
            1 for case in rendered if case["divergence"]["against_strict_rfc8032"]
        ),
        "cases_a_measured_cofactorless_verifier_disagrees_with": sum(
            1
            for case in rendered
            if case["divergence"]["against_observed_cofactorless"]
        ),
        "cases": rendered,
    }
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed corpus differs from a regeneration",
    )
    arguments = parser.parse_args(argv)

    generated = regenerate()
    if arguments.check:
        if not CORPUS.is_file():
            print(f"{CORPUS} does not exist", file=sys.stderr)
            return 1
        if CORPUS.read_text(encoding="utf-8") != generated:
            print(
                "the divergence corpus is not reproducible from its recorded inputs; "
                "run generate_ed25519_divergence_corpus.py",
                file=sys.stderr,
            )
            return 1
        document = json.loads(generated)
        print(
            f"ed25519 divergence corpus: reproducible; "
            f"{document['case_count']} cases, "
            f"{document['confirmed_case_count']} with a confirmed ZIP-215 verdict, "
            f"{document['diverging_case_count']} diverging"
        )
        return 0

    CORPUS.write_text(generated, encoding="utf-8")
    print(f"wrote {CORPUS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
