#!/usr/bin/env python3
"""Check every work unit in the breakdown against evidence rather than assertion.

`docs/implementation/PR_SIZED_WORK_BREAKDOWN.md` carries one block per work unit.
Each block must declare five fields — `Files:`, `Acceptance:`, `Depends:`, `Est:`
and `Status:` — and this validator decides whether the recorded status is
consistent with what is actually in the tree.

The mechanism is deliberately narrow. A unit's `Files:` line marks each path it
will *create* with the repository's existing `(new)` marker. Those paths are the
unit's promised artifacts, so their presence or absence is an observation rather
than a claim:

| Signal         | Meaning                                                    |
| -------------- | ---------------------------------------------------------- |
| `absent`       | the unit declares new artifacts and none of them exist      |
| `partial`      | some exist                                                  |
| `present`      | all of them exist                                           |
| `none-planned` | the unit creates no new file, so this check learns nothing  |

A recorded status must be consistent with its signal:

* `not-started` — the signal may not be `partial` or `present`. The moment
  somebody creates one of the unit's artifacts, this fails, which is the whole
  point: a stale `not-started` cannot survive the work starting.
* `landed` — the signal may not be `absent` or `partial`, and the status must
  name a commit this repository resolves.
* `superseded-by <ID>` — the named unit must have a heading in the same file.
* `in-progress` — deliberately unconstrained by the signal, because artifact
  presence cannot refute it. A unit that has authored its one new file and not
  yet touched the three existing files it also names looks `present` and is not
  finished. This is the weakest of the four statuses and the summary counts it
  separately for that reason.

`none-planned` units are reported separately and are never counted as confirmed.
A validator that hides how much it could not check is worse than one that checks
less, so the summary states three numbers rather than one.

Two further invariants, both mechanical:

* the dependency graph resolves and is acyclic, and `Est:` never exceeds the
  16-hour ceiling the document's own standard sets;
* every `create table` in `packages/schemas/planning-schema.sql` is named by at
  least one unit block, so a table cannot be persisted by nothing.

The derived status block in the document is generated by this script, so the
"what can be started now" list cannot drift from the statuses it summarises.

Exit codes: 0 when every check passes, 1 on any defect, 2 when an input cannot
be read.

Usage:
  validate_work_unit_status.py            # check
  validate_work_unit_status.py --write    # regenerate the derived block
  validate_work_unit_status.py --gate ID  # require ID's whole closure landed
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BREAKDOWN = ROOT / "docs" / "implementation" / "PR_SIZED_WORK_BREAKDOWN.md"
PLANNING_SQL = ROOT / "packages" / "schemas" / "planning-schema.sql"

HEADING_RE = re.compile(r"^###\s+([A-Z]{1,2}-\d{3})\b")
SECTION_RE = re.compile(r"^##\s")
FIELD_RE = re.compile(r"^(Files|Acceptance|Depends|Est|Status):\s*(.*)$")
INLINE_CODE_RE = re.compile(r"`([^`\n]+)`")
NEW_MARKER_RE = re.compile(r"^\s*\(new\)", re.IGNORECASE)
UNIT_ID_RE = re.compile(r"^[A-Z]{1,2}-\d{3}$")
EST_RE = re.compile(r"^(\d{1,3})(?:\s*-\s*(\d{1,3}))?$")
COMMIT_RE = re.compile(r"^[0-9a-f]{7,40}$")
CREATE_TABLE_RE = re.compile(
    r"^\s*create\s+table\s+(?:if\s+not\s+exists\s+)?([a-z_]+)", re.I
)

STATUS_VALUES = ("not-started", "in-progress", "landed", "superseded-by")
EST_CEILING_HOURS = 16

GENERATED_BEGIN = "<!-- generated: work-unit-status -->"
GENERATED_END = "<!-- end generated: work-unit-status -->"

# Which artifact signals each recorded status tolerates. `none-planned` is
# admitted everywhere because it is an absence of evidence, not evidence.
ALLOWED_SIGNALS = {
    "not-started": {"absent", "none-planned"},
    "in-progress": {"absent", "partial", "present", "none-planned"},
    "landed": {"present", "none-planned"},
    "superseded-by": {"absent", "partial", "present", "none-planned"},
}


class Failure(RuntimeError):
    """An input the validator needs could not be read."""


@dataclass
class Unit:
    unit_id: str
    line: int
    fields: dict[str, str] = field(default_factory=dict)
    field_lines: dict[str, int] = field(default_factory=dict)
    body: str = ""
    planned_paths: list[str] = field(default_factory=list)

    @property
    def signal(self) -> str:
        if not self.planned_paths:
            return "none-planned"
        present = [p for p in self.planned_paths if (ROOT / p).exists()]
        if not present:
            return "absent"
        if len(present) == len(self.planned_paths):
            return "present"
        return "partial"

    @property
    def status_word(self) -> str:
        return (
            self.fields.get("Status", "").split()[0]
            if self.fields.get("Status")
            else ""
        )

    @property
    def depends(self) -> list[str]:
        raw = self.fields.get("Depends", "").strip()
        if raw in ("", "none"):
            return []
        return [token.strip().strip("`") for token in raw.split(",") if token.strip()]


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as error:
        raise Failure(f"unreadable {path}: {error}") from error


def planned_paths(files_line: str) -> list[str]:
    """Return the paths this `Files:` line marks with the `(new)` marker.

    The marker binds to the token it follows, exactly as
    `validate_cross_references.py` reads it, so one planned deliverable in a list
    never speaks for the sibling beside it.
    """
    found: list[str] = []
    for match in INLINE_CODE_RE.finditer(files_line):
        token = match.group(1).strip()
        rest = files_line[match.end(1) :]
        # skip the closing backtick before looking for the marker
        rest = rest[1:] if rest.startswith("`") else rest
        if NEW_MARKER_RE.match(rest):
            found.append(token)
    return found


def parse_units(text: str) -> list[Unit]:
    units: list[Unit] = []
    current: Unit | None = None
    body: list[str] = []
    for number, line in enumerate(text.splitlines(), start=1):
        heading = HEADING_RE.match(line)
        if heading:
            if current is not None:
                current.body = "\n".join(body)
            current = Unit(unit_id=heading.group(1), line=number)
            units.append(current)
            body = []
            continue
        if SECTION_RE.match(line):
            if current is not None:
                current.body = "\n".join(body)
            current = None
            body = []
            continue
        if current is None:
            continue
        body.append(line)
        matched = FIELD_RE.match(line)
        if matched:
            name, value = matched.group(1), matched.group(2).strip()
            if name in current.fields:
                current.fields[f"__duplicate__{name}"] = value
            else:
                current.fields[name] = value
                current.field_lines[name] = number
            if name == "Files":
                current.planned_paths = planned_paths(value)
    if current is not None:
        current.body = "\n".join(body)
    return units


def commit_resolves(sha: str) -> bool:
    try:
        return (
            subprocess.run(
                ["git", "cat-file", "-e", f"{sha}^{{commit}}"],
                cwd=ROOT,
                capture_output=True,
                check=False,
            ).returncode
            == 0
        )
    except OSError:  # pragma: no cover - git is always present in this repository
        return False


def check_fields(unit: Unit, known: set[str], defects: list[str]) -> None:
    where = f"{unit.unit_id} (line {unit.line})"
    for name in ("Files", "Acceptance", "Depends", "Est", "Status"):
        if name not in unit.fields:
            defects.append(f"{where}: missing `{name}:`")
        if f"__duplicate__{name}" in unit.fields:
            defects.append(f"{where}: duplicate `{name}:`")
        elif not unit.fields.get(name):
            defects.append(f"{where}: empty `{name}:`")

    estimate = unit.fields.get("Est", "")
    matched = EST_RE.match(estimate)
    if not matched:
        defects.append(f"{where}: `Est:` is not an integer or a range: {estimate!r}")
    else:
        upper = int(matched.group(2) or matched.group(1))
        if upper > EST_CEILING_HOURS:
            defects.append(
                f"{where}: `Est:` upper bound {upper} exceeds the {EST_CEILING_HOURS}-hour ceiling; the unit must be split"
            )

    for dependency in unit.depends:
        if not UNIT_ID_RE.match(dependency):
            defects.append(f"{where}: `Depends:` holds a non-identifier {dependency!r}")
        elif dependency not in known:
            defects.append(
                f"{where}: `Depends:` names {dependency}, which has no heading"
            )
        elif dependency == unit.unit_id:
            defects.append(f"{where}: `Depends:` names itself")


def check_status(unit: Unit, known: set[str], defects: list[str]) -> None:
    where = f"{unit.unit_id} (line {unit.line})"
    raw = unit.fields.get("Status", "")
    word = unit.status_word
    if word not in STATUS_VALUES:
        defects.append(
            f"{where}: `Status:` is not one of {', '.join(STATUS_VALUES)}: {raw!r}"
        )
        return

    rest = raw[len(word) :].strip()
    if word == "landed":
        sha = rest.strip("()`")
        if not COMMIT_RE.match(sha):
            defects.append(
                f"{where}: `Status: landed` must name a commit; found {rest!r}"
            )
        elif not commit_resolves(sha):
            defects.append(
                f"{where}: `Status: landed` names {sha}, which this repository does not resolve"
            )
    elif word == "superseded-by":
        target = rest.strip("()`")
        if target not in known:
            defects.append(
                f"{where}: `Status: superseded-by` names {target!r}, which has no heading"
            )
    elif rest:
        defects.append(f"{where}: `Status: {word}` takes no argument; found {rest!r}")

    signal = unit.signal
    if signal not in ALLOWED_SIGNALS[word]:
        missing = [p for p in unit.planned_paths if not (ROOT / p).exists()]
        existing = [p for p in unit.planned_paths if (ROOT / p).exists()]
        detail = f"present={existing}" if word == "not-started" else f"absent={missing}"
        defects.append(
            f"{where}: `Status: {word}` contradicts the artifact signal `{signal}` ({detail})"
        )


def check_cycles(units: list[Unit], defects: list[str]) -> None:
    graph = {unit.unit_id: unit.depends for unit in units}
    state: dict[str, int] = {}

    def visit(node: str, trail: list[str]) -> None:
        if state.get(node) == 2:
            return
        if state.get(node) == 1:
            cycle = " -> ".join(trail[trail.index(node) :] + [node])
            defects.append(f"dependency cycle: {cycle}")
            return
        state[node] = 1
        for nxt in graph.get(node, []):
            if nxt in graph:
                visit(nxt, trail + [node])
        state[node] = 2

    for unit_id in graph:
        visit(unit_id, [])


def check_table_ownership(units: list[Unit], defects: list[str]) -> int:
    text = read_text(PLANNING_SQL)
    tables = [
        match.group(1)
        for match in (CREATE_TABLE_RE.match(line) for line in text.splitlines())
        if match
    ]
    named: set[str] = set()
    for unit in units:
        for token in INLINE_CODE_RE.findall(unit.body):
            candidate = token.strip()
            if candidate in tables:
                named.add(candidate)
    for table in sorted(set(tables) - named):
        defects.append(
            f"`{table}` in packages/schemas/planning-schema.sql is named by no work unit, so nothing owns persisting it"
        )
    return len(tables)


def closure(units: dict[str, Unit], root: str) -> set[str]:
    seen: set[str] = set()
    stack = list(units[root].depends)
    while stack:
        node = stack.pop()
        if node in seen or node not in units:
            continue
        seen.add(node)
        stack.extend(units[node].depends)
    return seen


def startable(units: list[Unit]) -> list[str]:
    """Units not yet landed whose every dependency has landed."""
    landed = {unit.unit_id for unit in units if unit.status_word == "landed"}
    ready = []
    for unit in units:
        if unit.status_word in ("landed", "superseded-by"):
            continue
        if all(dependency in landed for dependency in unit.depends):
            ready.append(unit.unit_id)
    return ready


def render_block(units: list[Unit]) -> str:
    counts = {value: 0 for value in STATUS_VALUES}
    for unit in units:
        if unit.status_word in counts:
            counts[unit.status_word] += 1
    checkable = [unit for unit in units if unit.signal != "none-planned"]
    ready = startable(units)

    lines = [
        GENERATED_BEGIN,
        "",
        f"Units: {len(units)}. Every one carries `Files:`, `Acceptance:`, `Depends:`, `Est:` and `Status:`.",
        "",
        "| Status | Units |",
        "|---|---|",
    ]
    for value in STATUS_VALUES:
        lines.append(f"| `{value}` | {counts[value]} |")
    lines += [
        "",
        f"Startable now — not landed, and every dependency landed: {len(ready)}.",
        "",
        ", ".join(f"`{unit_id}`" for unit_id in ready) + ".",
        "",
        f"Statuses checkable against artifact evidence: {len(checkable)} of {len(units)}. "
        f"The other {len(units) - len(checkable)} declare no new file in `Files:`, so this check "
        "can neither confirm nor refute them and does not claim to.",
        "",
        GENERATED_END,
    ]
    return "\n".join(lines)


def rewrite_block(text: str, block: str) -> str:
    start = text.find(GENERATED_BEGIN)
    end = text.find(GENERATED_END)
    if start == -1 or end == -1:
        raise Failure(
            f"{BREAKDOWN.name} has no generated status block; add {GENERATED_BEGIN} and {GENERATED_END}"
        )
    return text[:start] + block + text[end + len(GENERATED_END) :]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--write", action="store_true", help="regenerate the derived status block"
    )
    parser.add_argument(
        "--gate", metavar="ID", help="require every dependency of ID to be landed"
    )
    arguments = parser.parse_args(argv)

    try:
        text = read_text(BREAKDOWN)
        units = parse_units(text)
        if not units:
            raise Failure(f"{BREAKDOWN.name} declares no work-unit headings")
        known = {unit.unit_id for unit in units}
        defects: list[str] = []
        for unit in units:
            check_fields(unit, known, defects)
            check_status(unit, known, defects)
        check_cycles(units, defects)
        table_count = check_table_ownership(units, defects)
        block = render_block(units)
    except Failure as failure:
        print(f"work-unit status validation: ERROR\n- {failure}", file=sys.stderr)
        return 2

    if arguments.write:
        BREAKDOWN.write_text(rewrite_block(text, block), encoding="utf-8")
        print(f"regenerated the derived status block in {BREAKDOWN.relative_to(ROOT)}")
        return 0

    if block not in text:
        defects.append(
            "the derived status block is stale; run "
            "`python3 scripts/repository/validate_work_unit_status.py --write`"
        )

    if arguments.gate:
        by_id = {unit.unit_id: unit for unit in units}
        if arguments.gate not in by_id:
            print(
                f"work-unit status validation: ERROR\n- unknown unit {arguments.gate}",
                file=sys.stderr,
            )
            return 2
        for dependency in sorted(closure(by_id, arguments.gate)):
            if by_id[dependency].status_word != "landed":
                defects.append(
                    f"gate {arguments.gate}: {dependency} is `{by_id[dependency].status_word}`, not `landed`"
                )

    checkable = sum(1 for unit in units if unit.signal != "none-planned")
    summary = (
        f"{len(units)} units, {checkable} statuses checked against artifact evidence, "
        f"{len(units) - checkable} unverifiable by this check, {table_count} SQL tables owned"
    )

    if defects:
        print("work-unit status validation: FAIL", file=sys.stderr)
        for defect in defects:
            print(f"- {defect}", file=sys.stderr)
        print(
            f"work-unit status validation: FAIL ({len(defects)} defect(s); {summary})",
            file=sys.stderr,
        )
        return 1

    print(f"work-unit status validation: PASS ({summary})")
    print(
        "claim_scope=field-completeness-and-artifact-presence-only; a landed status is not a working feature"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
